<?xml version="1.0" encoding="utf-8"?><Database Name="client_db" Class="GamesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\client_db.mdf;Integrated Security=True" SettingsObjectName="Client.Properties.Settings" SettingsPropertyName="client_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TblGames" Member="TblGames">
    <Type Name="TblGame">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>